# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dac6f3495dbe070d90ccde1f2d2a1220a886de9920035020a88ae20635448962129ef1173c6538d8809cbaae1d19d393bb2e4d9dd1e2984153f0d6114443c7a2

test:
  secret_key_base: 308953be2189387dd3e9b0b27543631ee9e8737f1620dfcea9fc9391d69e223c220e8d19b0929a6f86878658ac362d9f4941b7f57dd6c9d4c5a3596eb7a27c31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
